spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test"
    username: "root"
    password: "manager"

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

api:
  openweathermap:
    key: ""